- .github/workflows/push-tokens.yml
GitHub action to automate pushing generated tokens in `/build/web/` directory to gc-ds-core for proof-of-concept.
Requires GitHub secrets :
- `API_TOKEN_GITHUB`: Personal access token
- `USER_EMAIL`: User email matching personal access token
If pushed forward, which account details will be filled out in the repo's secrets.
> Add GitHub action

- README.md
Adds an acute accent for _experimental_  in the Français link fragment within the README.md so that linking works.
> Fix Français link fragment

- build/figma/figma.tokens.json
- build/web/_variables.scss
- build/web/variables.css
- package.json
- tokens/base/typography/base.js
Rename paragraph token to text to represent all text and not just paragraphs.
> rename paragraph token to text

- build/figma/figma.tokens.json
- build/web/_variables.scss
- build/web/variables.css
- tokens/components/stepper/base.json
`gcds-components` repo accessibility tests flagged gcds-stepper for failing colour contrast.
Changing gcds-stepper text from `--gcds-color-grayscale-700`: `#747a82` to `--gcds-color-grayscale-900`: `#545961`.
> Fix gcds-stepper colour contrast

- .prettierrc
- build/figma/figma.tokens.json
- build/web/_variables.scss
- build/web/variables.css
- tokens/base/typography/base.js
- Added comments to calculateLineHeight to understand what is happening
- Made the code a bit more readable. I think?
- Added support for octaves. This allows us to fine tune our typographic rhythm
This prioritizes the reader a bit more than a strict baseline grid. 
An example before octaves. All lines are multiples of 26. H3 and H4 looks super spaced out, while h5 and h6 lines are jammed to each other
An example with 2 octaves. All lines are a multiple of 13 (26/2). H3 and H4 are a bit better. H2 H5 and H6 are still jammed together
Maybe its also about tuning the fontSize scale
> Commented and introduced octaves to calculateLineHeight.

- build/figma/figma.tokens.json
- build/web/_variables.scss
- build/web/variables.css
- config.js
- tokens/base/typography/base.js
We have tokens for individual typography attributes, but we can do a bit more for Figma by creating text styles containing all attributes needed to compose an h1, h2, label, etc. 
These are a bit more opinion based, but they also are optional and don't interfere with individual props. They also provide a useful shortcut to compose typography.
For css, we can also compose a [font shorthand declaration](https://developer.mozilla.org/en-US/docs/Web/CSS/font). Which could be equally useful as utilities to apply everything at once.
> Adding typography styles and transform to process as css/scss font prop.

- build/figma/figma.tokens.json
- build/web/_variables.scss
- build/web/variables.css
- package.json
- tokens/components/button/base.json
Add width tokens to the `gcds-button` component for full-width sizing on mobile.
> Add tokens to support mobile full-width buttons

- build/figma/figma.tokens.json
- build/web/_variables.scss
- build/web/variables.css
- package.json
- tokens/components/breadcrumbs/base.json
Adding new padding and margin tokens to `gcds-breadcrumbs` to address https://github.com/cds-snc/gcds-components/issues/152.
Used in https://github.com/cds-snc/gcds-components/pull/153
> Add new margin + padding tokens for gcds-breadcrumbs

- .github/workflows/publish.yml
Update the publish package workflow so that new packages are now also published to the CDN.
Each new package will be published to a versioned directory in the CDN and replace the files for its @latest version. This will allow users to either link to versioned assets or the latest files.
- cds-snc/gcds-components#168
- cds-snc/platform-core-services#322
> feat: publish new packages to CDN

- .github/workflows/publish.yml
Update the IAM role used to publish changes to the CDN.
- cds-snc/platform-core-services#322
> fix: use the correct OIDC role for the repo

- .github/workflows/publish.yml
Add a workflow step that posts a message to the Design System ops channel when the publish workflow fails.
- cds-snc/platform-core-services#333
> feat: Slack notify on publish workflow failure

- build/figma/figma.tokens.json
- build/web/_variables.scss
- build/web/variables.css
- package.json
- tokens/components/alert/base.json
- tokens/components/pagination/base.json
- [8c2aff2](https://github.com/cds-snc/gcds-tokens/commit/8c2aff2c03db5d3f7aa08ae0271f71a3d7a8fc74) - Remove alert active border + pagination border tokens
Notes:
Removing these two tokens as they can be replaced with `currentColor` in the components CSS.
> Update alert token

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/search.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/search.scss
- build/web/scss/tokens.scss
- package.json
- tokens/components/search/tokens.json
Change `border-radius` token in `gcds-search` to use `border-radius: value value value value` format. The bottom right of the search component was not properly reading the border radius values.
> Gcds search border-radius fix

- .github/workflows/publish.yml
This will be used to help calculate the deployment frequency for this
repo.
Currently it will only run if a package is published in the NPM Publish
step.
https://github.com/cds-snc/platform-core-services/issues/350
> feat: send deployment metrics to sentinel

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/heading.css
- build/web/css/global.css
- build/web/css/global/typography.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/heading.scss
- build/web/scss/global.scss
- build/web/scss/global/typography.scss
- build/web/scss/tokens.scss
- package.json
- tokens/components/heading/tokens.json
- tokens/global/typography/tokens.js
Adding new heading tokens and mobile font styles.
The new mobile font sizes are calculated with a base font size `16px` and a scale of `1.125`.
> Add heading tokens

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/link.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/link.scss
- build/web/scss/tokens.scss
- package.json
- tokens/components/link/tokens.json
This adds more tokens needed for the Link component.
Also got rid of the `active` styles because @nmakuch has confirmed that links would not contain styling for active state
This PR:
> chore: adds more design tokens for the link component

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/button.css
- build/web/css/components/checkbox.css
- build/web/css/components/input.css
- build/web/css/components/pagination.css
- build/web/css/components/radio.css
- build/web/css/components/select.css
- build/web/css/components/textarea.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/button.scss
- build/web/scss/components/checkbox.scss
- build/web/scss/components/input.scss
- build/web/scss/components/pagination.scss
- build/web/scss/components/radio.scss
- build/web/scss/components/select.scss
- build/web/scss/components/textarea.scss
- build/web/scss/tokens.scss
- package.json
- tokens/components/button/tokens.json
- tokens/components/checkbox/tokens.json
- tokens/components/input/tokens.json
- tokens/components/pagination/tokens.json
- tokens/components/radio/tokens.json
- tokens/components/select/tokens.json
- tokens/components/textarea/tokens.json
Add a box-shadow to multiple components to have consistent styling. Based on decision from Dev/Design sync on August 1st.
Updated component tokes:
- Button
- Checkbox
- Input
- Radio
- Pagination
- Select
- Textarea
> Add focus box-shadow to multiple components

- .github/workflows/publish.yml
Update the CDN publish step to sleep for `60s` so that the npm publish has time to complete.
> fix: give `npm publish` time to complete

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/error-summary.css
- build/web/css/components/stepper.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/error-summary.scss
- build/web/scss/components/stepper.scss
- build/web/scss/tokens.scss
- tokens/components/error-summary/tokens.json
- tokens/components/stepper/tokens.json
Remove redundant tokens after integrating `gcds-heading` component into existing components to reduce code duplication created through repeated text styles.
`gcds-heading` was integrated into:
- gcds-error-summary
- gcds-stepper
> refactor: remove redundant tokens after integrating gcds-heading into existing components

- build/figma/figma.tokens.json
- tokens/components/checkbox/tokens.json
- tokens/components/error-summary/tokens.json
- tokens/components/fieldset/tokens.json
- tokens/components/file-uploader/tokens.json
- tokens/components/input/tokens.json
- tokens/components/radio/tokens.json
- tokens/components/search/tokens.json
- tokens/components/select/tokens.json
- tokens/components/textarea/tokens.json
- tokens/global/color/tokens.json
Remove camel case naming convention from global `focus-text-form` token to match other tokens.
> fix: naming convention from global focus-text-form token

- CHANGELOG.md
Noticed the changelog needed a bit of a cleanup. I added dates to all the releases we did before adding release-please and removed all the `chore` updates that made it into the changelog during the initial release-please setup.
> chore: update changelog (remove chores + add dates)

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/radio.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/radio.scss
- build/web/scss/tokens.scss
- tokens/components/radio/tokens.json
Update `--gcds-radio-check-top` to `0.9375rem` to center the circle in a checked `gcds-radio-group`.
To test properly, use the [refactor/form-rewrite branch](https://github.com/cds-snc/gcds-components/tree/refactor/form-rewrite) on gcds-components.
> fix: update radio check top to be correct value

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/global.css
- build/web/css/global/color.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/global.scss
- build/web/scss/global/color.scss
- build/web/scss/tokens.scss
- tokens/global/color/tokens.json
As discussed in the dev-design-sync channel, we are removing the global `bg-black` background token as it's currently unused and doesn't provide a clear purpose.
> refactor: remove global black background token

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/error-summary.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/error-summary.scss
- build/web/scss/tokens.scss
- tokens/components/error-summary/tokens.json
Keep red error colour for error summary links.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/899)
> refactor: revert red error colour for error summary links

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/global.css
- build/web/css/global/typography.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/global.scss
- build/web/scss/global/typography.scss
- build/web/scss/tokens.scss
- tokens/global/typography/tokens.js
Change monospace font from `Menlo` to `Noto Sans Mono` to have all fonts hosted in the same spot and update fallback to `monospace`.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/911)
> refactor: change monospace font to noto sans mono

- README.md
Added instructions on how to use the GCDS Design Tokens
- https://github.com/cds-snc/design-gc-conception/issues/989
> docs: add instructions on how to use design tokens

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/base.css
- build/web/css/base/color.css
- build/web/css/global.css
- build/web/css/global/color.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/base.scss
- build/web/scss/base/color.scss
- build/web/scss/global.scss
- build/web/scss/global/color.scss
- build/web/scss/tokens.scss
- tokens/base/color/tokens.json
- tokens/global/color/tokens.json
Add new `purple-700` base colour token to use as the new global token for the link visited state.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/gcds-components/572)
> feat: add global link visited token

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/label.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/label.scss
- build/web/scss/tokens.scss
- tokens/components/label/tokens.json
Required form labels are currently using a bold font-weight when they should be using a regular font-weight. Adding a new font weight token for the required label.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1082)
> fix: required label font weight

- build/figma/figma.tokens.json
- build/web/css/.css
- build/web/css/components.css
- build/web/css/components/fieldset.css
- build/web/css/tokens.css
- build/web/scss/.scss
- build/web/scss/components.scss
- build/web/scss/components/fieldset.scss
- build/web/scss/tokens.scss
- tokens/components/fieldset/tokens.json
The required text in fieldset legends is currently using the same font as the rest of the legend. Switch to using body font sizing and weight.
> fix: fieldset legend required font

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/notice.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/notice.scss
- build/web/scss/tokens.scss
- tokens/components/notice/tokens.json
Based on https://github.com/cds-snc/design-gc-conception/issues/1283, update Notice heading spacing to match design.
To be used with https://github.com/cds-snc/gcds-components/pull/627
> fix: Notice heading spacing

- .github/workflows/publish.yml
This PR adds a check if the package is already published on npm or not. It proceeds to skip the publish action and continues to the update CDN part
> ci: gh actions add ignore if package already exists

- build/figma/figma.tokens.json
- build/web/css/global.css
- build/web/css/global/typography.css
- build/web/css/global/typography/font.css
- build/web/css/tokens.css
- build/web/scss/global.scss
- build/web/scss/global/typography.scss
- build/web/scss/global/typography/font.scss
- build/web/scss/tokens.scss
- tokens/global/typography/font.json
As part of the rewrite, it became clear that we are currently not using the global font token for `label`. It isn't used in the code, or the design. We removed it to avoid confusion about which styles to use for non-heading text.
> refactor: remove global font token for label

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/grid.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/grid.scss
- build/web/scss/tokens.scss
- tokens/components/grid/tokens.json
Removing the old grid gap token as it's been replaced with the more flexible options added in [this PR](https://github.com/cds-snc/gcds-tokens/pull/375).
> remove: remove old grid gap token

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/lang-toggle.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/lang-toggle.scss
- build/web/scss/tokens.scss
- tokens/components/lang-toggle/tokens.json
To match requirements for mandatory elements alignment, add font tokens to language toggle component tokens.
- Language toggle uses `16px` font for desktop as is required for elements in the header.
- Language toggle uses `18px` font with a font weight of `700`/`bold` on mobile.
- Bumped vertical padding from `spacing-100` to `spacing-125` to allow mobile link to be compliant with AAA standards
https://github.com/cds-snc/design-gc-conception/issues/1333
To be tested with https://github.com/cds-snc/gcds-components/pull/741
> feat: Update language toggle tokens for mandatory elements alignment

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/breadcrumbs.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/breadcrumbs.scss
- build/web/scss/tokens.scss
- tokens/components/breadcrumbs/tokens.json
To match requirements for mandatory elements alignment, add font token to breadcrumb item component tokens.
- Breadcrumbs uses size `16px` font since it is a sub-component of the header.
https://github.com/cds-snc/design-gc-conception/issues/1354
To be used with https://github.com/cds-snc/gcds-components/pull/742
> feat: Add breadcrumb item font token

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/lang-toggle.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/lang-toggle.scss
- build/web/scss/tokens.scss
- tokens/components/lang-toggle/tokens.json
Adjust language toggle padding from `{spacing.125.value} {spacing.150.value}` to `{spacing.100.value} {spacing.125.value}` to match design in figma.
> fix: adjust language-toggle padding to match design

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/search.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/search.scss
- build/web/scss/tokens.scss
- tokens/components/search/tokens.json
To match requirements for mandatory elements alignment, update search component tokens.
Search component tokens that are no longer in use will be removed in a separate pull request tagged `remove:` once this pull request has been merged.
https://github.com/cds-snc/design-gc-conception/issues/1335
- Set search to only use `16px` font as it is a sub-component of the header
- Change the border colour to `grayscale-100`
- Remove border radius
- Adjust padding to match font updates
- Reduce border width to `1px`
To be used in https://github.com/cds-snc/gcds-components/pull/743
> feat: Update search component tokens

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/search.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/search.scss
- build/web/scss/tokens.scss
- tokens/components/search/tokens.json
To align the search with mandatory elements alignment add tokens for placeholder colour, width and height.
For https://github.com/cds-snc/gcds-components/pull/743
> feat: Add search tokens for width, height and placeholder colour

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/breadcrumbs.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/breadcrumbs.scss
- build/web/scss/tokens.scss
- tokens/components/breadcrumbs/tokens.json
For mandatory elements alignment, adjust margins on breadcrumbs item to have a smaller gap between items, from `12px` to `8px`.
For https://github.com/cds-snc/gcds-components/pull/742
> fix: Breadcrumb item margins

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/date-modified.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/date-modified.scss
- build/web/scss/tokens.scss
- tokens/components/date-modified/tokens.json
To match the requirements for the alignment of the mandatory elements, add a font token to the date-modified component tokens and update the `margin-top` token to `40px`.
- Date-modified text uses size 16px font since it is a sub-component of the footer.
- Date-modified margin-top is set to 40px.
The [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1266) for the requested change.
> feat: add date-modified font token + update margin-top value

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/footer.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/footer.scss
- build/web/scss/tokens.scss
- tokens/components/footer/tokens.json
To match the requirements for the alignment of the mandatory elements, the heading font of the footer component needs to be updated and a new footer font token needs to be added.
- Heading fonts remain set to Lato, and non-heading fonts remain set to Noto
- Headings should be H3 and should be the mobile sizing ( font-size: 26px or 1.625rem, line-height: 30px or 2rem)
- Heading font weights remain set to 700
- Link size is set to 16px (1rem) on desktop to align with Canada.ca
- Link size is set to 16px (1rem) on mobile to align with Canada.ca
The [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1266) for the requested change.
I will remove the old `--gcds-footer-font-heading-desktop` and …
> feat: add footer font token + update heading font

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/footer.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/footer.scss
- build/web/scss/tokens.scss
- tokens/components/footer/tokens.json
Updating the footer spacing to align with the new design. The new design introduces a bit more consistency in the spacing, especially for the following 3 things:
- Consistent margin bottom value for headings (`spacing-300`)
- Consistent grid gap spacing for all lists (`spacing-300`)
- Consistent band padding for all 2 bands: contextual, main & sub (`spacing-450`)
For the signature width tokens, I noticed that the naming of the token could be optimized. For example, the old signature token `--gcds-footer-sub-sm-width` is now named `--gcds-footer-sub-signature-sm-width` to create a clear connection between the token and the signature.
As part of this refactor, many of the old padding & margin tokens are no longer used. I will remove them in a separate PR.
> refactor: update footer spacing tokens

- build/figma/figma.tokens.json
- build/web/css/components.css
- build/web/css/components/search.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/search.scss
- build/web/scss/tokens.scss
- tokens/components/search/tokens.json
To maintain the visual focus style used on search and keep it aligned with other components in the GC Design System, add a focus border and margin tokens. Used border width for the margin token to directly tie the margin to the border size.
For review feedback from https://github.com/cds-snc/gcds-components/pull/743
> fix: maintain focus style for search

- build/figma/figma.tokens.json
- build/tailwind/tailwind.tokens.json
- build/web/css/base.css
- build/web/css/base/color.css
- build/web/css/components.css
- build/web/css/components/button.css
- build/web/css/tokens.css
- build/web/scss/base.scss
- build/web/scss/base/color.scss
- build/web/scss/components.scss
- build/web/scss/components/button.scss
- build/web/scss/tokens.scss
- config/tailwind/v3.x.x/tailwind.config.js
- config/tailwind/v4.x.x/css-config/src/input.css
- config/tailwind/v4.x.x/js-config/tailwind.config.js
- tokens/base/color/tokens.json
- tokens/components/button/tokens.json
For alignment with design.canada.ca, add component tokens for new button role start.
- new button role tokens
- New disabled token to set opacity to `50%`
- Small padding updates for all buttons
**Note:** To be used with https://github.com/cds-snc/gcds-components/pull/775
> feat: Start button component tokens

- config/tailwind/v3.x.x/tailwind.config.js
- config/tailwind/v4.x.x/css-config/src/input.css
- config/tailwind/v4.x.x/js-config/tailwind.config.js
We are incorporating the default GCDS focus style as custom `focus` class into our new Tailwind config files. This update allows users to seamlessly apply the same GCDS focus styles to their Tailwind projects as those used in the GCDS components.
[Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1487) for this new feature.
> feat: add custom focus class for interactive elements to Tailwind configs

- config/tailwind/v3.x.x/src/input.css
- config/tailwind/v3.x.x/tailwind.config.js
- config/tailwind/v4.x.x/css-config/src/input.css
- config/tailwind/v4.x.x/js-config/src/input.css
- config/tailwind/v4.x.x/js-config/tailwind.config.js
We are incorporating a new custom `bg-full-width` class into our new Tailwind config files. This update allows users to apply a class that allows an element to stretch beyond its container’s edges, creating a background effect that extends across the entire screen.
Zenhub ticket
[Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1486) for this new feature.
> feat: add custom full-width-bg class to tailwind configs

- build/figma/figma.tokens.json
- build/tailwind/tailwind.tokens.json
- build/web/css/components.css
- build/web/css/components/nav-group.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/nav-group.scss
- build/web/scss/tokens.scss
- tokens/components/nav-group/tokens.json
Issue: https://github.com/cds-snc/gcds-components/issues/770
When using mobile Safari browser to browse a site/app with a large amount of menu items in the top-nav/side-nav. The last item in the menu list can be covered by the URL bar. To fix this the padding-bottom for the mobile menu has been increased to `--gcds-spacing-950` in the `--gcds-nav-group-mobile-padding` component token.
1. With original padding values, create a page with a `gcds-side-nav` with many nav links.
2. View the page on a mobile Safari browser.
3. Notice the last nav link will be hidden and not accessible to click.
4. Update `--gcds-nav-group-mobile-padding` to the new value.
5. View the page on a mobile Safari browser.
6. Notice the last nav link will now be above the URL bar.
> fix: mobile menu padding for Safari mobile

- config/tailwind/v4.x.x/css-config/src/input.css
Updating the Tailwind config for version 4 (CSS) to be limited to GC Design System colours only. The Tailwind config for version 4 (JS) and version 3 are already set to only use GC Design System colours.
[Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1485) for this change.
> feat: limit colours to gcds colours for Tailwind CSS config version 4

- build/figma/figma.tokens.json
- build/tailwind/tailwind.tokens.json
- build/web/css/components.css
- build/web/css/components/footer.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/footer.scss
- build/web/scss/tokens.scss
- tokens/components/footer/tokens.json
Updating the spacing between the links in the footer sub band to align with GC Web.
[Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1552) for this change.
> fix: update spacing between links in footer sub band

- build/figma/figma.tokens.json
- build/tailwind/tailwind.tokens.json
- build/web/css/components.css
- build/web/css/components/nav-group.css
- build/web/css/components/top-nav.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/nav-group.scss
- build/web/scss/components/top-nav.scss
- build/web/scss/tokens.scss
- tokens/components/nav-group/tokens.json
- tokens/components/top-nav/tokens.json
As part of the new design for the top-nav component, we no longer need the some tokens for the top-nav and nav-group.
The following top-nav and nav-group tokens will be removed because they will no longer be used in the new top-nav design:
- --gcds-nav-group-top-nav-trigger-margin-inline-start
- --gcds-top-nav-background
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1352) for the changes.
The token changes for the top-nav design update can be found in [PR #440](https://github.com/cds-snc/gcds-tokens/pull/440).
> remove: remove old nav-group token

- build/figma/figma.tokens.json
- build/tailwind/tailwind.tokens.json
- build/web/css/components.css
- build/web/css/components/nav-group.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/nav-group.scss
- build/web/scss/tokens.scss
- tokens/components/nav-group/tokens.json
Adjust padding for the nav-group component to align properly with the nav-links in the top-nav.
Fixes [this issue](https://github.com/cds-snc/gcds-components/issues/824).
> fix: adjust nav-group padding to align with nav links

- build/figma/figma.tokens.json
- build/tailwind/tailwind.tokens.json
- build/web/css/components.css
- build/web/css/components/nav-group.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/nav-group.scss
- build/web/scss/tokens.scss
- tokens/components/nav-group/tokens.json
The following nav-group token will be removed because it will no longer be used in the nav-group
- --gcds-nav-group-top-nav-trigger-border-width
Part of the fix for [this issue](https://github.com/cds-snc/gcds-components/issues/824).
> remove: old nav-group top-nav trigger token

- build/figma/figma.tokens.json
- build/tailwind/tailwind.tokens.json
- build/web/css/components.css
- build/web/css/components/nav-group.css
- build/web/css/tokens.css
- build/web/scss/components.scss
- build/web/scss/components/nav-group.scss
- build/web/scss/tokens.scss
- tokens/components/nav-group/tokens.json
Update the background colour of the `nav-group` component to `white` if it is used within a `top-nav` to match the new design of the `top-nav` component.
> feat: change nav-group bg to white within top-nav to match new design
