cds-snc/gcds-tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, config.js, generate-figma-tokens.js
Tests on building new tokens from Figma without interfering with with the dev->design workflow
=> chore: Clean up current token builds

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/base/brand/base.json, tokens/components/button/base.json, tokens/components/checkbox/base.json, tokens/components/error-message/base.json, tokens/components/input/base.json, tokens/components/label/base.json, tokens/components/radio/base.json, tokens/components/site-menu/base.json
Add tokens for new checkbox and radio components.
Changed all components to use new brand design tokens for better maintainability.
=> Add brand and radio/checkbox component tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/banner/base.json
=> add banner component tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/verify-banner/base.json
=> add verify banner tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/select/base.json
Add tokens for select component.
=> add tokens for select component

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/fieldset/base.json
Add tokens for the `gcds-fieldset` component.
=> Add fieldset tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/file-uploader/base.json
=> add file-uploader tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/stepper/base.json
=> add gcds-stepper tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/base/color/base.json, tokens/components/alert/base.json, tokens/components/banner/base.json, tokens/components/site-menu/base.json
Add tokens for alert component
=> add tokens for alert component

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/details/base.json
Add tokens for the gcds-details component.
=> add gcds-details tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/banner/base.json
Remove `destructive` and `warning` role from the banner component in order to better separate the alert and the banner component.
=> gcds-banner: remove destructive + warning role

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/checkbox/base.json, tokens/components/radio/base.json
Update tokens to match styling of checkbox and radio hint.
=> Update tokens to match design

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/link/base.json
Add link tokens to support link classes in the utility framework.
=> add link tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/button/base.json
Update button tokens to reflect updated design.
=> gcds-button: update button tokens for new design

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/pagination/base.json
Add tokens for the `gcds-pagination` component.
=> Add pagination tokens

.github/workflows/build.yml
Add build action on pull request into main branch.
=> Add build action on PR

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/base/typography/base.js, tokens/components/breadcrumbs/base.json
- Add tokens for breadcrumbs component
- We are using a medium font weight for the breadcrumbs, therefore I'm adding a medium font weight to our font weights.
=> add tokens for breadcrumb component

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/base/color/base.json
The values for blue 100 and 500 were wrong. They were using grayscale hex codes. Probably a mistake
=> Fix wrong blue 100 and 500 values

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/footer/base.json, tokens/components/header/base.json
Adjust header and footer margin tokens to fix display issues.
=> Header footer margin

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/alert/base.json
Add missing tokens for alert component.
=> add alert tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/site-menu/base.json
Add container token to site-menu component. The rest will follow when we restyle the site-menu.
=> Add container token to site-menu

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/alert/base.json, tokens/components/checkbox/base.json, tokens/components/details/base.json, tokens/components/footer/base.json, tokens/components/radio/base.json, tokens/global/border/base.json, tokens/global/color/base.json
- Update global link colours
- Fix checkbox font token
- Update global border tokens
- Revert hint text colour back to black
=> Update to global tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/breadcrumbs/base.json
Move margin token from breadcrumb item to breadcrumb container to help address a11y issue in breadcrumb component.
=> Move margin to breadcrumbs from item

README.md
Adding the french translation for the readme.
=> add french readme

README.md, package.json
Update package information for v1 release
=> Version 1 update

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/base/color/base.json, tokens/components/file-uploader/base.json, tokens/global/color/base.json
- add border to gcds-file-uploader remove button
- add new text-secondary text colour
- update disabled text colour for better colour contrast
=> Update text secondary colour

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, tokens/components/site-menu/base.json
Update `gcds-site-menu` sub menu backgrounf colour from `{color.greyscale.300}` to `{color.greyscale.100}` for better contrast.
=> Update sub-menu background colour to lighter colour

package.json
Update version and homepage to new doc site url
=> Update package.json homepage and version

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/breadcrumbs/base.json, tokens/components/details/base.json
- Creating some new tokens for the details component
- Creating some new tokens for the breadcrumbs component
=> new tokens for breadcrumbs and details components

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/lang-toggle/base.json
- New tokens for lang-toggle PR
- This should be merged before looking at [PR #150](https://github.com/cds-snc/gcds-components/pull/150)
=> lang-toggle tokens

build/figma/figma.tokens.json, build/web/_variables.scss, build/web/variables.css, package.json, tokens/components/error-summary/base.json
Add error summary to component tokens.
**Tokens are created for this pull request https://github.com/cds-snc/gcds-components/pull/144**
=> Add error summary component

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/card.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/card.scss, build/web/scss/tokens.scss, package.json, tokens/components/card/tokens.json
Add token for `gcds-card` description max-width.
=> Add missing card description token

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/container.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/container.scss, build/web/scss/tokens.scss, package.json, tokens/components/container/tokens.json
- Add new container component tokens
=> add container component tokens

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/card.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/card.scss, build/web/scss/tokens.scss, package.json, tokens/components/card/tokens.json
- Updated and fixed border and border-radius tokens for `gcds-card`
=> Card token fix

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/container.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/container.scss, build/web/scss/tokens.scss, package.json, tokens/components/container/tokens.json
Add a border token for the container component.
=> Add border to container component

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/search.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/search.scss, build/web/scss/tokens.scss, package.json, tokens/components/search/tokens.json
Add component tokens for `gcds-search` component
=> Gcds search

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/header.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/header.scss, build/web/scss/tokens.scss, package.json, tokens/components/header/tokens.json
Remove unused header token `--gcds-header-brand-search-width`
=> Cleanup header component tokens

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/file-uploader.css, build/web/css/components/pagination.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/file-uploader.scss, build/web/scss/components/pagination.scss, build/web/scss/tokens.scss, package.json, tokens/components/file-uploader/tokens.json, tokens/components/pagination/tokens.json
- These tokens are for [GCDS COMPONENTS PULL 221](https://github.com/cds-snc/gcds-components/pull/221)
=> token update for changes from token review

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/details.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/details.scss, build/web/scss/tokens.scss, package.json, tokens/components/details/tokens.json
Update details tokens for new elements in `gcds-details`.
Provides tokens for https://github.com/cds-snc/gcds-components/pull/237
=> Details update

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/link.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/link.scss, build/web/scss/tokens.scss, package.json, tokens/components/link/tokens.json
Tokens for the new Link component
=> feat: new tokens for link component

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/heading.css, build/web/css/components/text.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/heading.scss, build/web/scss/components/text.scss, build/web/scss/tokens.scss, package.json, tokens/components/heading/tokens.json, tokens/components/text/tokens.json
- Add gcds-text tokens
- Add character limit tokens for gcds-heading
=> Add text tokens

CHANGELOG.md, package.json
=> Update CHANGELOG.md to v1.9.2

.github/workflows/release_generator.yml
Adds a [release generator](https://github.com/googleapis/release-please) to this repository
Related to
- https://github.com/cds-snc/design-gc-conception/issues/569
=> feat: add release generator

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/link.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/link.scss, build/web/scss/tokens.scss, tokens/components/link/tokens.json
Adds token for link underline offset value
=> chore: add new token for link (underline offset)

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/link.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/link.scss, build/web/scss/tokens.scss, tokens/components/link/tokens.json
Adds new design tokens to the link component
=> chore: update link tokens

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/link.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/link.scss, build/web/scss/tokens.scss, tokens/components/link/tokens.json
Adds box-shadow to the focus styles
=> chore: add focus box-shadow to link token

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/link.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/link.scss, build/web/scss/tokens.scss, tokens/components/link/tokens.json
Removes link token for focus border color
=> chore: remove link token focus-border-color

.github/workflows/release_generator.yml, release-please-config.json
Updates release please to newest version and hide chores from changelog
=> chore: hide chores from changelog, update release please action

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/link.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/link.scss, build/web/scss/tokens.scss, tokens/components/link/tokens.json
Add mobile font size to the link component.
=> feat: add mobile font-size to link component

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/checkbox.css, build/web/css/components/fieldset.css, build/web/css/components/hint.css, build/web/css/components/label.css, build/web/css/components/radio.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/checkbox.scss, build/web/scss/components/fieldset.scss, build/web/scss/components/hint.scss, build/web/scss/components/label.scss, build/web/scss/components/radio.scss, build/web/scss/tokens.scss, tokens/components/checkbox/tokens.json, tokens/components/fieldset/tokens.json, tokens/components/hint/tokens.json, tokens/components/label/tokens.json, tokens/components/radio/tokens.json
[Zenhub ticket input](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/716)
[Zenhub ticket checkbox](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/662)
[Zenhub ticket radio](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/661)
Note: new token package has to be added to [PR #498](https://github.com/cds-snc/gcds-components/pull/498)
=> refactor: design updates for input, label, fieldset, radio, checkbox

CHANGELOG.md
Adding French translations for the last few changelog updates.
=> docs: add french translations for changelog

.github/workflows/publish.yml
Sends a message to private channel #ds-design-dev when a release is published on npm
Thanks @sylviamclaughlin for creating the slack webhook, I've created a new secrets env called `SLACK_WEBHOOK_DSNDEV`
=> ci: slack channel notify on release

.github/workflows/publish.yml
Fixes the wrong link slackbot posts to the channel
=> fix: wrong link

.github/workflows/publish.yml
=> fix: invalid env for version on slack message

README.md
Adding the french translation for the updated README content
https://docs.google.com/document/d/16ncOJvbAhC-fnQXhH7j_k2DnaveSTZCtVBCRsPABkTw/edit
=> docs: update README french section

CHANGELOG.md, release-please-config.json
Improving the changelog by:
- Moving the release date below the version heading and adding the text "Released on:".
- Adding some emojis to easier recognize each section of changes.
=> Improve changelog

build/figma/figma.tokens.json, build/web/css/.css, build/web/css/components.css, build/web/css/components/notice.css, build/web/css/tokens.css, build/web/scss/.scss, build/web/scss/components.scss, build/web/scss/components/notice.scss, build/web/scss/tokens.scss, tokens/components/notice/tokens.json
Fix the naming of the font tokens for the type text of the notice component and add new margin token.
=> fix: Notice tokens names + add margin token

.github/workflows/publish.yml
=> ci(fix): update gh action to publshing

.github/workflows/publish.yml
change  the way we get the package version
=> ci(fix):get version from package.json

.github/workflows/publish.yml
=> ci(fix): update run script on check if package exists

catalog-info.yaml
Another repo with the metadata updated with the proper System and Owner values
=> feat: update metadata fo point to System and Owner team

build/figma/figma.tokens.json, build/web/css/components.css, build/web/css/components/details.css, build/web/css/tokens.css, build/web/scss/components.scss, build/web/scss/components/details.scss, build/web/scss/tokens.scss, tokens/components/details/tokens.json
Improving the design for the details component when it is being printed. 
[Report issue ticket](https://github.com/cds-snc/gcds-components/issues/700).
=> style: improve print design for details component

CHANGELOG.md
Adds the french translation for the changelog (release 2.0.1)
=> chore(changelog): update changelog FR

release-please-config.json
Update available release-please sections. We are removing the `Style` section as most changes in this repo are style-related and will add a new `Remove`  section for tokens that are permanently removed without replacement.
=> chore: update release please sections

build/tailwind/tailwind.tokens.json, config.js, config/tailwind/v3.x.x/src/input.css, config/tailwind/v3.x.x/tailwind.config.js, config/tailwind/v4.x.x/css-config/src/input.css, config/tailwind/v4.x.x/js-config/src/input.css, config/tailwind/v4.x.x/js-config/tailwind.config.js, package.json
This PR introduces example configuration files for integrating GCDS tokens into Tailwind. It provides configuration files for both Tailwind `v3.x.x` and Tailwind `v4.x.x`. These configurations will help users apply GCDS tokens (such as colors, spacing, typography) to their Tailwind projects.
The build folder now also provides a Tailwind-specific JSON output. Users previously used the Figma JSON file to map GCDS tokens to their Tailwind config.
Tailwind configuration file that maps GCDS tokens into Tailwind’s `Tailwind.config.js` configuration file for version 3.x.x.
Tailwind configuration file that maps GCDS tokens into Tailwind’s `Tailwind.config.js` configuration file for version 4.x.x.
Tailwind configuration file that maps GCDS tokens into [Tailwind’s new CSS based configuration …
=> feat: add tailwind example config files using gcds tokens

build/figma/figma.tokens.json, build/tailwind/tailwind.tokens.json, build/web/css/components.css, build/web/css/components/heading.css, build/web/css/tokens.css, build/web/scss/components.scss, build/web/scss/components/heading.scss, build/web/scss/tokens.scss, tokens/components/heading/tokens.json
Updating H1 border colour to align with design.
[Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1455) for this change.
=> fix: update h1 border colour

build/figma/figma.tokens.json, build/tailwind/tailwind.tokens.json, build/web/css/components.css, build/web/css/components/link.css, build/web/css/tokens.css, build/web/scss/components.scss, build/web/scss/components/link.scss, build/web/scss/tokens.scss, tokens/components/link/tokens.json
Reduce link offset spacing to match Figma link component.
=> fix: reduce link offset spacing
